name: CI
# Specify which GitHub events will trigger a CI build

on: push
# Define a single job, build

jobs:
  build:
    # Specify an OS for the runner
    runs-on: ubuntu-latest

    #Define steps
    steps:

      # Firstly, checkout repo
      - name: Checkout repository
        uses: actions/checkout@v2
      # Set up Python env
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      # Install dependencies
      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt
      # Test with pytest
      - name: Copy Pytest scripts
        run: |
          python3 cp_tests.py
      - name: Run pytest
        run: |
          pytest
      - name: Remove Pytest scripts
        run: |
          python3 rm_tests.py

